spring:
  datasource:
    username: root
    password: 35440
    url: jdbc:mysql://localhost:3306/my_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        globally_quoted_identifiers: true
        jdbc:
          time_zone: UTC
  mail:
    host: smtp.gmail.com
    port: 587
    username: grow.and.pull@gmail.com
    password: lmwa ugxz mtam nxvw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
#jwt:
#  confirm_expiration: 2629743000
#  access_expiration: 2629743000
#  reset_password_expiration: 2629743000

